apiVersion: v1
kind: Secret
metadata:
  name: firebase-secret
type: Opaque
data:
  firebase.json: | 
    ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZGF0YWJhc2Ut
    Y2hhdHRpbmctYXBwIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiZGMwODk1ODkzOTA4NWZjZmJiOTk0
    NDk4ZjQ0ZDNkOTZhNjc2ZDI5NSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFU
    RSBLRVktLS0tLVxuTUlJRXZ3SUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2t3Z2dTbEFnRUFB
    b0lCQVFEN3huZFJFZUJVL0JOTlxuZ2x6eVE3SjBDanJpQ0JwY3MvaFRWbFQ4VkNlcTA5Zk9HV1Ji
    VHQzYU1jNjVMZjEvMTFmYmY4TThtMk0vNDYweVxuOVhGSmNWQkY0SDlJTmE0Tk1XQ3VGVDQvOU9T
    ZDlWdDhUdkJWa1RTZHpvSzR0KzdFNUc2ZGVjRU9iS0VCT2kxcVxuTXBnRDlTYnBIdWRoaEJZdlY1
    TldVNm40VTBGazNvM2c0VFRSVkV3b05MbERnSDhHRVVWZ3d4cStvVGhFWUpPR1xuUGJyVXBXcGJ3
    dVdta2s4MVlzNmx2L3lkbnVqeDdkanhYVWJ6R01mTElucWwwT1UyVW1hK2puQy9NQ1RxUjV0L1xu
    aEh6QTdJaHBaZEpvTjAzKzBtSlRHTUJ5cXIrUkFwV1pNRGc3RVlLbnRXZ0Y2N3ArclhXeS9WdkRv
    NmFnQ0xKalxucCsvNm1VeVRBZ01CQUFFQ2dnRUFhVXJKR0ZMSkJkRjdneFVyS0xmTitBQlZPclRY
    ellBSU1GWHc2YXVLQVVOaFxudzFQVUorbFdGMHR3SC9wUFF2ajhTWlBuUXIvYkpGdGpVZVhhVURQ
    K3RaSmF1SWlXZHZiNDd5UjhLWVFSWGN1L1xuekQ4NC9CZmpNTUd0NG5FdGZoTG4vWnh1ODhqVEZt
    L05rVldDUkZsd1FkckdPZjVpeHI2eG84OE9USWNJMkpUelxuMTBkYUNRUzdacFQ2MmhRUVJabFJK
    MEoydXI3NEhhRXkweEVWRXREa2NOcWdJWDBjMHBJREQ2M1JLQjJxSWlVM1xucDJtNExxTkJqUnBu
    SDV1cFB6cDhVRXlKMHMyYU9SSlB0WE10cmtjTlNNeXVRRHRGWWYwSWdJdjdZb3JMMnloOVxuT1g0
    NnY1dUhEV01UOWxYQjlmQjRSczN2OWZLSXBkUktDbCtxU0x2cm9RS0JnUUQveTM2R0RUWGMycXFZ
    UklURVxuQ1owd2FPaDdFTXliNHZ0RU1ENC9yMHlLZWQ3a2IrSE9Ud1JycHhsSHY5eXphMTVhUUU5
    U2FybTFtL0ljK2xjeVxuL2lEZXFnYy9zWFFKZkdkcGMvWFNBcEdNamQrMnlkbFk0ZzU5YVNVc1RB
    dEZoaUZUajlKc2FDU1ZzaHFKZFAwcFxuUUR2akhhTkxzNEp5am8rQ200ZkU5WkpvY3dLQmdRRDcr
    aVdSeUtDN0lFOHNGbHZXR0cvUXk3YmVUaUEwYzgyT1xuR2djeDZ0Q3dBVnV5NXRneW9SNmxWWHRS
    RTlublZDTWViQ1ZtSklScG9hbDJwcUpqc3hXYVlWaUhxMiticnA2Q1xucWxHb2dKUnNOaEl5UlNv
    NmliYTBtcUNhV2sxamZGQUFDRFEwajRIK2RhcXl3NzgwRzUwUWpUYlhoWFMwNXpaOFxudnZxNGNN
    Z2pZUUtCZ1FEbk82SEl0TEI0VWdQZFdqTmF0QVl3K09VUU93TjcrQmlFYjhnVjhmWVRTRkJCMlJJ
    YlxuV2pyNHhqbUlMdHpvSkt0S2t0QWlCUENVUjhENmlTUENxUkExdVNhTVlYSXdFUkc2dG1VRnor
    U2JWclZobTk2clxuQnM5cWQxNXZTTjczbm1VS0VQMTdtamxZU1lUTHRjSVZSRWZlNjYvdWd2dnRh
    d280V3pqRXgrbnVHUUtCZ1FEQlxuTWFIc2pLN3Z5bTNwbDVzQ0krcFhaRm5wU0cxWXloRW9pcnhK
    Z1loUDZqcXNpR0hyTDYyWGhscnVaeElEVTNjNVxudENGWWwxY094bXh3RklNZGZnbHFQSWpzUEgx
    dUdBeGdrc1haTS95WW16eUlYbzlxSW54N0xMTkdwVVlBcVNlTlxuWHJ6b0w3K3pvZlFtNi82RnJV
    WlhrbTRpQUtqaXF3UVQwVG5hZ0Y1ekFRS0JnUURhazJHT1BwYmJUOURKdVJ5a1xuaGJmZmZHTE10
    MWFDUjBoN1hONnY5dEVSaE9QMkVad2hiZ0dzUU0wU3FyUzFCOUgzU3EyOEJUU3l2YnBNMEVkL1xu
    TmpzZmRGZDhhem8yS2JoRmk4c1BaWmJjQmQ2bGVWYlY1WlA3RG9jVHRURWR5MnF5M25JanowWk9X
    SjlhSmNQRlxuY2FDKzU3a2JFWU94aW13K3c2RkpqV1RHSEE9PVxuLS0tLS1FTkQgUFJJVkFURSBL
    RVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImRhdGFiYXNlLWhhbmRsZXJAZGF0YWJhc2Ut
    Y2hhdHRpbmctYXBwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEw
    MTYyMDM5NTU2ODc3OTUwMDQzNCIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29v
    Z2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdv
    b2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0
    dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5
    X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRh
    L3g1MDkvZGF0YWJhc2UtaGFuZGxlciU0MGRhdGFiYXNlLWNoYXR0aW5nLWFwcC5pYW0uZ3NlcnZp
    Y2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo=
